### register user
POST http://localhost:3000/auth/reg
Content-Type: application/json

{
    "email":"choudharydhanraj239@gmail.com",
    "password":"admin@123"
}

### login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"choudharydhanraj239@gmail.com",
    "password":"admin@@123"
}
### forget pass
POST http://localhost:3000/auth/forget-pass
Content-Type: application/json

{
    "email":"choudharydhanraj239@gmail.com",
    "password":""
}
### verify otp and update pass
POST http://localhost:3000/auth/verify-otp
Content-Type: application/json

{
    "email":"choudharydhanraj239@gmail.com",
    "otp":"382317",
    "password":"admin@@123"
}
### protected routs
POST http://localhost:3000/auth/users
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob3VkaGFyeWRoYW5yYWoyMzlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeWdXWmhQUy9LNDlFOEgydVZNYlkzZUpQSlcxL0s4V2U1bk4vRUIzdi5IeHVZMzdHS0pCNzIiLCJpYXQiOjE3MTA0MTEyNzAsImV4cCI6MTcxMDQxNDg3MH0.hNrKTKEwkmtREgQiPwS93L8RA79Q1J05-5_mlGoLcDw

