### products
GET http://localhost:3000/product/products
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob3VkaGFyeWRoYW5yYWoyMzlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcGxNN293SldrYzRSM0k2Y3UwSjBmdWNPclVQL2ZsRXRSek9UQUNNd3U2Mm1PcGhkNXZRMkciLCJpZCI6IjY1ZmFiYWNjZjEwNzcyNzU3NGZhZGQ2NSIsImlhdCI6MTcxMDkzMDYzNiwiZXhwIjoxNzEwOTM0MjM2fQ.YM5rMXpOus9F5Z4_3Q7vzpplIqielfTxsW0ZrliWB5w

### products
GET http://localhost:3000/product/product/1
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob3VkaGFyeWRoYW5yYWoyMzlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkL0NDdTdQWDVzZnRoRVBFZExvb1RBT2pkYTFaekZTL2tERzFJVjZiWERrZ3VLYmxMMEhsTG0iLCJpYXQiOjE3MTA5MTgwMzYsImV4cCI6MTcxMDkyMTYzNn0.iCczTZWcm9HGpLvV91DNpbwhhx6HfaV9XB88bUgL6fc

### products
POST http://localhost:3000/product/create
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob3VkaGFyeWRoYW5yYWoyMzlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkL0NDdTdQWDVzZnRoRVBFZExvb1RBT2pkYTFaekZTL2tERzFJVjZiWERrZ3VLYmxMMEhsTG0iLCJpYXQiOjE3MTA5MTgwMzYsImV4cCI6MTcxMDkyMTYzNn0.iCczTZWcm9HGpLvV91DNpbwhhx6HfaV9XB88bUgL6fc

### products
PUT http://localhost:3000/product/update/1
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob3VkaGFyeWRoYW5yYWoyMzlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkL0NDdTdQWDVzZnRoRVBFZExvb1RBT2pkYTFaekZTL2tERzFJVjZiWERrZ3VLYmxMMEhsTG0iLCJpYXQiOjE3MTA5MTgwMzYsImV4cCI6MTcxMDkyMTYzNn0.iCczTZWcm9HGpLvV91DNpbwhhx6HfaV9XB88bUgL6fc

### products
DELETE  http://localhost:3000/product/del/1
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob3VkaGFyeWRoYW5yYWoyMzlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkOWEuY0tiM2xLZVJzemkuNTFDL1h3T3IzNGdUVTBpQ2IySGF5TEQ3U2ZZcDlmZFZVcWxpeVciLCJpYXQiOjE3MTA5MzAwNjcsImV4cCI6MTcxMDkzMzY2N30.KZhsjCARA1MyItn6IRPBRDzV6a0q9_oABf4KG1ehH8M